---
- name: install PostgreSQL
  hosts: all
  become: yes
  tasks:
    - name: install PostgreSQL and dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql-server
        - postgresql-contrib

    - name: initialise PostgreSQL
      command: postgresql-setup initdb

    - name: start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: yes